# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="sorin"

# Set to this to use case-sensitive completion
export CASE_SENSITIVE="true"

# Vagrant
export VAGRANT_HOME=~/.vagrant.d

# Pyenv
export PATH="${HOME}/.pyenv/bin:$PATH"
export PYENV_ROOT="${HOME}/.pyenv"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

#source ~/.bin/tmuxinator.zsh

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)

plugins=(git vagrant django tmux tmuxinator)
if [ `uname` = "Darwin" ]; then
   plugins+=(brew osx)
fi

if [ `uname` = "Linux" ]; then
   plugins+=(archlinux)
fi

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

. `brew --prefix`/etc/profile.d/z.sh

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
source ~/.zshalias
source ~/.zshenv

# Bindings
bindkey -e

# If vim mode, than bind this key, can't live without
# CTRL-R
# bindkey "^r" history-incremental-search-backward

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

PERL_MB_OPT="--install_base \"/Users/joeri/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/joeri/perl5"; export PERL_MM_OPT;
